### PR TITLE
Compatibility with jsonapi-resources@0.9.7

### LINKED ISSUE #93: Relax jsonapi-resources dependency
jsonapi-resources version is now locked to 0.9.0. 0.9.2 has been recently released, but can't be used with jsonapi-utils.

### PR DESCRIPTION
**Pull request by krasnoukhov**
Tests are passing.

So far it seems like the only breaking change was this: https://github.com/cerebris/jsonapi-resources/commit/970bc7922bc162fb36cb5e67f511a8b63b45024f

Closes #93

### CODE REVIEW

**Comment by krasnoukhov** [comment]
Not sure why Travis does not run here, but here's a build: https://travis-ci.org/simplepractice/jsonapi-utils/builds/509436787

**Comment by krasnoukhov** [comment]
Tested against an internal suite (~600 examples), does not look like there are any issues

**Comment by jafffmen** [comment]
Hello! Could you tell me what's the status of this?

**Comment by krasnoukhov** [comment]
I just updated this for latest version (0.9.7)

**Comment by tiagopog** [comment]
Hi, @krasnoukhov. Thanks for contributing and sorry for the delay on reviewing it.

**Pull request merged**
