### PR TITLE
Fix double request parsing for default actions

### LINKED ISSUE #28: Should implementers always define controller actions?
_This is a question/confirmation issue and not a bug/code flaw issue._

When using JSONAPI::Utils, are the controller actions expected to explicitly be defined?

When mixing in JSONAPI::Utils, [we also get the JSONAPI::ActsAsResourceController module](https://github.com/b2beauty/jsonapi-utils/blob/master/lib/jsonapi/utils.rb#L13) and its behavior. [Within that module](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb), default actions are defined.

The first sentence in the ["How does it work?" section of the README](https://github.com/b2beauty/jsonapi-utils#how-does-it-work) made me think more about it:

> One of the main motivations behind JSONAPI::Utils is to keep things explicit in controllers so that developers can easily understand and maintain code.

With a primary motivation being explicit controller behavior, does that in turn mean that explicit controller actions are implied?

**Context**

While test driving some resources using JSONAPI::Utils + JSONAPI::Resources, I noticed that my immutable endpoints were working without defining any actions. At the time, I did not know why, and the specs were green so I let it be.

Recently, I encountered some trouble attempting to add a fully mutable resource, in particular with PATCH requests. After verifying that the API request body was correct, I narrowed the issue down to double parsing of the request ([once in JSONAPI::Utils](https://github.com/b2beauty/jsonapi-utils/blob/master/lib/jsonapi/utils/request.rb#L10-L16) and a [second time](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb#L66-L68) in the default action definition in JSONAPI::Resources).

The double parsing happened since it passed through a before filter than used the RequestParser instance and then entered the default update action which initialized a second RequestParser instance.

While looking closer at the specs for JSONAPI::Utils, I noticed that the controllers were always defining the actions. This led me back to the README, since I figured that I must have missed something.

To sum it up, I think that I have been doing it wrong (from the JSONAPI::Utils perspective) and I am looking for confirmation. 😄

### LINKED ISSUE #44: Adding JSONAPI::Utils to controller causes PATCH operations to malfunction
_Affects jsonapi-utils `0.5.0.beta4`, jsonapi-resources `0.8.1` and Rails `5.0.0.1`._

Given a model `SampleModel`:

```ruby
class SampleModel < ApplicationRecord
  # name: :string
end
```

And a resource `SampleModelResource`:

```ruby
class SampleModelResource < JSONAPI::Resource
  attributes :name
end
```

With controllers:

```ruby
class JsonApiController < JSONAPI::ResourceController
  include JSONAPI::Utils
end

class SampleModelsController < JsonApiController
end
```

And routes:

```ruby
Rails.application.routes.draw do
  jsonapi_resources :sample_models
end
```

And a controller spec that performs a patch operation:

```ruby
require 'rails_helper'

describe SampleModelsController, type: :controller do
  before do
    request.headers['Content-Type'] = "application/vnd.api+json"
  end

  describe 'PATCH #update' do
    subject { patch :update, params: params, body: body.to_json }

    let(:params) { { id: id } }
    let(:body) { { data: { id: id, type: 'sample_models', attributes: { name: 'bar' } } }
    let(:sample_model) { SampleModel.new(name: 'foo').tap { |m| m.save } }
    let(:id) { sample_model.id }
    
    it { expect(subject.status).to eq(200) }
  end
end
```

Running PATCH raises a `400 Bad Request`, which manifests as:

```
{"errors":[{"title":"A key is required","detail":"The resource object does not contain a key.","code":"109","status":"400"}]}
```

I dug deeper, and what I found was that `JSONAPI::Utils` adds a Rails callback that creates a `JSONAPI::RequestParser` [prior to the request being processed](https://github.com/tiagopog/jsonapi-utils/blob/master/lib/jsonapi/utils/request.rb#L11):

```ruby
def setup_request
  @request ||=
    JSONAPI::RequestParser.new(
      params.dup,
      context: context,
      key_formatter: key_formatter,
      server_error_callbacks: (self.class.server_error_callbacks || [])
    )
end
```

This ends up running [some code in jsonapi-resources](https://github.com/cerebris/jsonapi-resources/blob/release-0-8/lib/jsonapi/request_parser.rb#L629) which parses the data parameters for the PATCH operation. In the process of parsing this data, it performs a `delete` on the data hash.

```ruby
def parse_single_replace_operation(data, keys, id_key_presence_check_required: true)
  fail JSONAPI::Exceptions::MissingKey.new if data[:id].nil?

  key = data[:id].to_s
  if id_key_presence_check_required && !keys.include?(key)
    fail JSONAPI::Exceptions::KeyNotIncludedInURL.new(key)
  end

  data.delete(:id) unless keys.include?(:id)

  # ...
end
```

Now the `JSONAPI::Utils` callback finishes without issue. However, when `JSONAPI::RequestParser`is invoked again as Rails runs the actual action, the `data` hash in `params` no long has `id`, which is required. It raises a `MissingKey` error, and the request fails.

##### In summary...

It seems like calling `JSONAPI::RequestHelper` twice with the same parameters is not safe. Despite `JSONAPI::Util`'s effort to `params.dup` prior to invoking it, the `JSONAPI::RequestHelper` code still modifies the underlying `data` hash in a pretty bad way.

Frankly, this seems to be more of an issue with `jsonapi-resources` than `jsonapi-utils`. But I thought I'd bring it to your attention, because as it stands, it means one cannot compose your package into a JSON API controller.

Are there any feasible workarounds? Or should an issue be opened with `jsonapi-resources`?

### PR DESCRIPTION
**Pull request by tiagopog**
Fixes #28 and #44

## TODO

- [x] Fix double request instantiation for default actions by overriding the `JSONAPI::ActsAsResourceController#process_request` method  – it's no longer required to override the default actions in order to skip this behavior;
- [x] Write specs covering the case for default actions;
- [x] Improve `README.md`;
- [x] Improve code doc;
- [x] Update version;
- [x] Update `.travis.yml`.

### CODE REVIEW

**Comment by tiagopog** [comment]
👀  @yellow5 @delner

**Comment by delner** [comment]
So I just spotted this in the Rails 5.0.1 release notes:

> Added ActionController::Parameters#deep_dup which actually creates a params copy, instead of refereing to old references in params.

> Fixes #26566.

https://github.com/rails/rails/issues/26566

It's possible that using `deep_dup` on that params object instead of `dup` in 5.0.1 might circumvent this entire issue. Worth trying?

**Comment by tiagopog** [comment]
Cool! I didn't know about the existence of that method, thanks for sharing.

It's certainly an easy fix for that issue of changing the internals of `params`, however, it would still make double instantiation on the `@request` instance variable , which I'm also trying to fix with this PR.

The fix proposed here – override the `JSONAPI::ActsAsResourceController#process_request` – will probably be temporary since the proper fix would be a [memoization on `@request`](https://github.com/cerebris/jsonapi-resources/pull/932).

**Comment by yellow5** [comment]
👍  👏

**Pull request merged**
